# Generated by Django 3.2 on 2021-05-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmitter', '0002_tmeet_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmeet',
            old_name='created_at',
            new_name='tmeeted_date',
        ),
    ]
