# Generated by Django 3.2 on 2021-06-08 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmitter', '0006_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='fav_from',
            new_name='fav_user',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='tmeet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faved_user', to='tmitter.tmeet'),
        ),
    ]
