# Generated by Django 3.2 on 2021-06-08 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tmitter', '0007_auto_20210608_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='fav_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faved_tmeet', to=settings.AUTH_USER_MODEL),
        ),
    ]
