# Generated by Django 3.2 on 2021-06-10 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tmitter', '0008_alter_favorite_fav_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='fav_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='tmeet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='tmitter.tmeet'),
        ),
    ]
